### ISSUE TITLE
Vaadin 24 Notifications are emtpy

### ISSUE THREAD

**Issue by simasch** [mvysny/karibu-testing#149]
I have to tests that check for the content of a notification:

```java
Notification notification = _get(Notification.class);
assertThat(notification.getElement().getOuterHTML()).isEqualTo("""
    <vaadin-notification suppress-template-warning>
     <template>
      Series saved
     </template>
    </vaadin-notification>""");
```

The notification is found but it's always empty.

**Comment by mvysny** [comment]
Hi Simon, could you please try calling `NotificationsKt.expectNotifications("Series saved")` whether that works?

Alternatively you can call https://github.com/mvysny/karibu-tools/blob/main/src/main/kotlin/Notifications.kt#L25 to obtain the notification text - since Vaadin 24 the text is no longer present in the HTML but is stored in the `text` property.

**Comment by simasch** [comment]
Hi @mvysny 
Thanks! Works great.
