### ISSUE TITLE
Behavior of BasicUtils.kt autoDiscoverViews has changed from version 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#15]
The package name we are passing to this method is in the form of **com.x.y.z.admin** and works fine in 1.0.1.  When we use version 1.0.2 no views are discovered

The ScanResult doesn't seem to be finding anything, i.e. **scanResult.getClassesWithAnnotation(Route::class.java.name)** 
returns an empty list.  I look at ScanResult and all of the maps seem to be empty.  Any ideas?

**Comment by mvysny** [comment]
Karibu-Testing 1.0.1 used Atmosphere internal code to find classes; however Atmosphere detector did not support finding classes that implement particular interface (e.g. `HasErrorParameter`). Therefore Karibu-Testing 1.0.2 switched to [ClassGraph](https://github.com/classgraph/classgraph) which works quite well for me... I wonder what happened so that it doesn't work for you.

Couple of ideas:
1. You can try to upgrade Karibu-Testing to 1.0.6 maybe there was something fixed related to auto-discovery.
2. You can try to upgrade classgraph dep to 4.6.23 since KT uses 4.6.3 which is quite old - there could be a couple of bug fixes which could help.
3. In the worst case you can include Atmosphere and populate `Routes.routes` by using Atmosphere classpath scanner instead of using `Routes.autoDiscoverViews()`.

Please let me know whether any of the above helped. Thanks!

**Comment by nbabb** [comment]
Option 2 worked for me (upgrading to io.github.classgraph:classgraph:4.6.28).  You can consider this issue closed as far as I'm concerned.  Thanks for the suggestions!

**Comment by mvysny** [comment]
Good to hear, thanks for letting me know! I've v-bumped classgraph version to 4.6.28 in https://github.com/mvysny/karibu-testing/commit/b7c203628913d53144ce7d55926ce670f1578f22 and the fix will be present in KT 1.0.7.
