### ISSUE TITLE
MockRouteAccessDeniedError causes different behaviour in Karibu vs Production

### ISSUE THREAD

**Issue by F43nd1r** [mvysny/karibu-testing#179]
The `MockRouteAccessDeniedError` introduced because of #161 causes a behaviour change for tests when the application provides a `HasErrorParameter<NotFoundException>`, but no `HasErrorParameter<AccessDeniedException>`.

Expected behaviour would be a redirect to NotFound from AccessDenied, instead an exception is thrown.
Workaround for me is 
```kotlin
 routes.errorRoutes.remove(MockRouteAccessDeniedError::class.java)
```

**Comment by mvysny** [comment]
That is correct. However, in development mode, a different page is shown, with HTTP 200 OK:
```
Could not navigate to 'admin'

Reason: Access is denied by annotations on the view.

Available routes:

    [<root>](http://localhost:8080/)
    [admin](http://localhost:8080/admin)
    [login](http://localhost:8080/login)
    [user](http://localhost:8080/user)

This detailed message is only shown when running in development mode.
```
The question is, what kind of behavior would we want for Karibu Testing to emulate:

1. Show the development mode page
2. Emulate production mode behavior and redirect to `HasErrorParameter<NotFoundException>`
3. Throw the `AccessDeniedException` (as done by `MockRouteAccessDeniedError`).

My thoughts are that 3. is preferable in Unit Testing: if an exception is thrown during testing, the test wants to learn and throw the original exception, so that the test failure can be analyzed and the cause can be understood quickly. In this case, if an `AccessDeniedError` is thrown, I'd want to see the exception. Redirecting to a dev-mode page or a `NotFoundException` would mask the original exception and would confuse me.

What do you think?

**Comment by F43nd1r** [comment]
Hm, I can see the argument for 3, but as I was upgrading old tests I'm gonna stick with 2.
Is my workaround your preferred solution to switch to production behaviour? If so maybe it could be documented.

**Comment by mvysny** [comment]
Now that I'm thinking about it, I think your workaround is a very good solution to enable behavior 2: it basically disables Karibu-Testing's "hack" to force Vaadin to use solution 3, which basically reverts Vaadin to use its own standard behavior (which is described in 2).

Let me update the documentation.

**Comment by mvysny** [comment]
I've updated the README documentation to mention this topic. Please feel free to review and offer suggestions if need be.
