### ISSUE TITLE
MockVaadinSession.setErrorHandler fails to be called in the event of an error.

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#27]
Hello Martin,

I am setting an error handler VaadinSession.setErrorHandler, and this is where I launch an error dialog.  I see in the test environment the session is an instance of MockVaadinSession.

The issue is that this handler doesn't seem to be called in the event of an application exception.  

Any help/advice is appreciated.  Thanks.

**Comment by mvysny** [comment]
Hey, thanks for reaching out!

Unfortunately this is an inherent problem with Karibu Testing. You see, in an app running in a servlet container the Vaadin error handler is run by VaadinServlet when the exception "bubbles" up the stack until it hits VaadinServlet. However, with Karibu Testing the exception never hits VaadinServlet because it's JUnit who's calling Vaadin methods.

I could hook into JUnit and pass any exception to the error handler, but I don't think that makes much sense since what you usually want to do is to simply fail the test on exception as soon as possible.

However, if you wish to test the error handler itself, you can simply invoke the error handler from a JUnit test, and then assert that a dialog has been shown.

Please let me know if the above covers your use-case; if not, just let me know.

**Comment by nbabb** [comment]
Hey Martin, thanks for the explanation.  And your suggestion is actually what I ended up doing, i.e. calling the handler directly.  Thanks for the response.
