### ISSUE TITLE
DataProvider does update Grid on refreshAll()

### ISSUE THREAD

**Issue by jstueckrath** [mvysny/karibu-testing#32]
I currently try to write a test with Karibu, but fail due to a data provider that just does not want to provide new data.

I have an application, where a user can define a filter and then press a button to apply that filter. The button forwards the filter to a `ConfigurableFilterDataProvider` of a `Grid` and then calls `refreshAll()` (on the data provider) to force the grid to update itself. This works fine in practice, but not in my test. There I can see that the button is clicked, the click listener is executed, `refreshAll()` is called, but the data provider does not even attempt to retrieve new data.

Debugging showed that there is an additional data provider listener when I start the application normally, but I do not think this has an effect. I currently suspect that the problem lies in the listener that is registered by the `DataCommunicator.handleAttach()` method. This indirectly calls `DataCommunicator.requestFlush()` which has the following check:
```java
if (!context.isClientSideInitialized()) {
  reset();
  arrayUpdater.initialize();
}
```

Could it be that mocking the client side impedes the behaviour here (the entire condition always evaluates to true)? Do you know of any similar issues? If yes, is there a way to avoid this problem and still use Karibu?

P.S.: I am using karibu-testing-v10:1.1.23 and Vaadin 14.1.17.

**Comment by mvysny** [comment]
> There I can see that the button is clicked, the click listener is executed, refreshAll() is called, but the data provider does not even attempt to retrieve new data.

That's exactly how Vaadin works. When the button is clicked, a request is made to the server. In that request the click handler is called, and from that handler you call `refreshAll()`. However, the server-side Grid doesn't attempt to fetch new data - it simply tells client-side Grid that it should refresh. The decision to actually fetch the data is then made by the client-side Grid, and it will fetch the data in a separate request.

However, Karibu-Testing doesn't run the client-side code and doesn't emulate this behaviour. This is an inherent limitation of Karibu-Testing. But there is a workaround. With Karibu-Testing we generally assume that the client-side Vaadin code works properly and the Grid would fetch new data properly. Thus, instead of emulating client-side code, I assert on the state of the DataProvider directly.

What I do is that I click the button (which sets the new filter), and then I assert that the Grid has certain number of rows (`_expectRows()`) and the first row contains these-and-these particular values (`_expectRow()`). These functions will go directly to Grid's `DataProvider` (which is now configured with the filter since the button has been clicked) and poll the data directly from the DataProvider itself, by directly calling the `DataProvider.fetch()` method.

Sorry for this wall of text, please let me know if this makes any sense :)

**Comment by jstueckrath** [comment]
This makes a lot of sense. Until now I did not know that the grid only tells the client that it should request a fetch and assumed that no client is involved (yet).

I also did not know that `_expectRows()` triggers the data provider. Thank you a lot, I should be able to use that to build my tests. :)
