### ISSUE TITLE
Idea for testing polimere sub components

### ISSUE THREAD

**Issue by chrisw73** [mvysny/karibu-testing#36]
Hi Martin! Nice talking yesterday ;-).

I tried an Idea yesterday and want to know, if you think it is good :-). Currently I am testing a class which is a subcomponent without a route, so I have to get the parent component with the route first as of your documentantion. I have tried the following, it worked well, so:

I extended the class I want to test in the same package - but in the test folder. There I applied a test route via which is found in the test. Here is my code:

@Route("testBv")
public class MyFormTestRoute extends MyForm {

    public MyFormTestRoute(MyService myService) {
        super(myService);
    }
}

And in the test:
    @Test
    public void fieldBinding() {
        UI.getCurrent().navigate(MyFormTestRoute.class);

        MyForm myForm = _get(MyForm.class);

        myForm.setBean(createMyBean());

        assertEquals(myForm.myFiled.getValue(), "MyVal");
    }

What do you think?

**Comment by mvysny** [comment]
Hey, nice to talk to you too :)

Actually you can test a subcomponent just by itself - it doesn't have to be a part of a route or attached to the UI:

```
@Test
public void fieldBinding() {
    MyForm myForm = new MyForm(); // or created by Spring from ctx

    myForm.setBean(createMyBean());

    assertEquals(myForm.myFiled.getValue(), "MyVal");
}
```

You can also use the local `_get()` function: the global one looks up stuff in entire UI, the local one looks inside of given component, e.g. `_get(myForm, Button.class)`. However I assume that MyForm is a PolymerTemplate and so in this particular case the lookups will not work.

If need be and the component needs to be attached (because for example it does some work in onAttach listener, perhaps fetches data lazily), you can simply attach the component to the UI:

```
@Test
public void fieldBinding() {
    MyForm myForm = new MyForm(); // or created by Spring from ctx
    UI.getCurrent().add(myForm);

    myForm.setBean(createMyBean());

    assertEquals(myForm.myFiled.getValue(), "MyVal");
}
```

What do you think? Please let me know whether this would work for you - if yes, I'll update the documentation to mention these specific cases.

**Comment by chrisw73** [comment]
Kewl! 
MyForm myForm = new MyForm(); 
This did not work without Karibu :-).

Thanks a lot.
The one thing I'd need now is to trigger a ClientSide ValueChangeEvent in a TextField...

**Comment by mvysny** [comment]
> MyForm myForm = new MyForm();  // This did not work without Karibu :-).

Yup, that might be because Karibu-Testing hooks into the PolymerTemplate loader and is thus able to load the template files from the project directory.

> The one thing I'd need now is to trigger a ClientSide ValueChangeEvent in a TextField...

There is no direct support for this yet from Karibu-Testing, but you can work around the issue:

```java
ComponentUtil.fireEvent(textField, new AbstractField.ComponentValueChangeEvent<TextField, String>(this, this, textField.getValue(), true);
```

But I'll add a direct support for that :+1:

**Comment by mvysny** [comment]
New API has been added:

* Kotlin, Groovy: `textField._fireValueChange()`
* Java: `LocatorJ._fireValueChange(textField)`

Added to Karibu-Testing 1.1.25, 1.2.1
