### ISSUE TITLE
Login doesn't work on Spring

### ISSUE THREAD

**Issue by DennisDavari** [mvysny/karibu-testing#47]
Hello guys, I want to test my application with Karibu and before all tests I want to login but I get the error 

```
java.lang.AssertionError: /login: No visible LoginOverlay in UI[] matching LoginOverlay: []. Component tree:
└── UI[]
    └── RouteNotFoundError[]
        ├── Html[]
        └── Html[
```

In order to simulate the login I use this:

```
	UI.getCurrent().navigate("login");
	LoginFormKt._login(_get(LoginOverlay.class), "admin", "password");
```

I use the login class of Spring Security. Does someone have an idea why this doesn't work?

**Comment by mvysny** [comment]
Hi Dennis,

 from the quick glance it looks like the `/login` route has not been discovered, since the `RouteNotFoundError` component is present in the current UI.

You need to auto-discover views by calling `routes = new Routes().autoDiscoverViews("com.vaadin.tshirtshop");` and then configure SpringServlet in a special way. See https://github.com/mvysny/t-shirt-shop-example for details.

**Comment by DennisDavari** [comment]
> Hi Dennis,
> 
> from the quick glance it looks like the `/login` route has not been discovered, since the `RouteNotFoundError` component is present in the current UI.
> 
> You need to auto-discover views by calling `routes = new Routes().autoDiscoverViews("com.vaadin.tshirtshop");` and then configure SpringServlet in a special way. See https://github.com/mvysny/t-shirt-shop-example for an example of a working Spring app.
> 
> Please let me know whether this helped.

Thank you for your answer. These statements were already added. What I am doing is that I am programming an online banking simulator with a group of other students. This right here is the code of the test class. 

       @SpringBootTest
        public class ApplicationTest {

	private static Routes routes;
	@Autowired
	private ApplicationContext ctx;

	@Autowired
	private UserRepository userRepo;

	@Autowired
	private BankAccountRepository accountRepo;

	@BeforeAll
	public static void discoverRoutes() {
		routes = new Routes().autoDiscoverViews("com.gravitasbankingsim.bankingsim");
	}

	@BeforeEach
	public void setup() {
		SpringServlet servlet = new MockSpringServlet(routes, ctx);
		MockVaadin.setup(UI::new, servlet);
	
			UI.getCurrent().navigate("login");
		LoginFormKt._login(_get(LoginOverlay.class), "admin", "password");
		userRepo.deleteAll();
		accountRepo.deleteAll();
		// TODO: Clear data repository
	} 
	@AfterEach
	public void tearDown() {
		MockVaadin.tearDown();
	}
}

So what we want to do is to simulate a login before each test so that we can perform the actual tests. I didn't include the actual tests since they are not necessary for solving the problem I think. We also have the class MockSpringServlet. At the end of this comment is the class MockSpringServlet. One group member told me that his tests used to work until new views were added to our project. Thank you for taking your time to help us.

        class MockSpringServlet extends SpringServlet {
	private static final long serialVersionUID = -4645523758071367886L;
	private final Routes routes;
	private final ApplicationContext ctx;

	public MockSpringServlet(Routes routes, ApplicationContext ctx) {
		super(ctx, false);
		this.routes = routes;
		this.ctx = ctx;
	}

	@Override
	public void init(ServletConfig servletConfig) throws ServletException {
		routes.register(servletConfig.getServletContext());
		super.init(servletConfig);
	}

	@Override
	protected VaadinServletService createServletService(DeploymentConfiguration deploymentConfiguration)
			throws ServiceException {
		VaadinServletService service = new SpringVaadinServletService(this, deploymentConfiguration, ctx) {
			private static final long serialVersionUID = 6532389652585519510L;

			@Override
			protected boolean isAtmosphereAvailable() {
				return false;
			}

			@Override
			public String getMainDivId(VaadinSession session, VaadinRequest request) {
				return "ROOT-1";
			}
		};
		service.init();
		return service;
	}
}

**Comment by LeoVerto** [comment]
Hi Martin, I'm another student from Dennis' group, thank you very much for your help so far!

After updating our testing code to closely follow your t-shirt-shop example (thanks for adding the jdoc comments!) and adding an explicit LoginView instead of relying on Spring Security's magic I've fixed our routing problem.

However now the problem appears to be that even after successfully logging in using `LoginFormKt._login` the Spring Security `SecurityContextHolder` appears to be `null` causing downstream failures wherever our app tries to get the current user.

Is this an obvious mistake on our part or does Karibu not support Spring Security?

Even when following the [vaadin flow login tutorial](https://vaadin.com/learn/tutorials/modern-web-apps-with-spring-boot-and-vaadin/adding-a-login-screen-to-a-vaadin-app-with-spring-security) down to a t we get errors like this:
```
/login: No visible Grid in UI[] matching Grid: []. Component tree:
└── UI[]
    └── LoginView[width:100% justify-content:center align-items:center height:100%]
        ├── H1[text='Gravitas Banking Simulator']
        └── LoginForm[DISABLED]
```
This appears to indicate some sort of failure to either set or to save the SecurityContext correctly, right?

**Comment by mvysny** [comment]
Hi, thank you @LeoVerto for additional information, that is indeed the source of the problem!

What Spring Security does is that it intercepts all HTTP calls and if there's no user logged in, it redirects to a Spring-provided login page. The login page then performs a POST with username and password, which is then intercepted by Spring, which then sets the `SecurityContextHolder` and redirects back to the root page.

All this interception happens on the Servlet Container level - Spring probably registers a bunch of Servlet Filters into the Servlet Container (Tomcat by default) which handle this behaviour.

Unfortunately, Karibu-Testing doesn't run the Servlet Container at all. Karibu-Testing only mocks enough of the environment around Vaadin to make Vaadin work, but nothing more. Therefore, the Spring Filters are not registered, and therefore there is nothing that can intercept a redirect to `/login`. This is a fundamental design trait of Karibu-Testing; we can only work around this limitation.

I can see the following workarounds:
1. Believe that Spring is configured correctly, pretend that the login happened, and set the `SecurityContextHolder` value manually.
2. Introduce LoginView and set the `SecurityContextHolder` value manually upon login. The problem here is that when the app is run, Spring will most probably intercept `/login` and will show its own login dialog instead of `LoginView`. That makes the tests testing something tnat's not really used in production; therefore I'd avoid this solution.
3. Disable Spring Security and handle the security yourself, using Vaadin's `BeforeEnterListener` registered to the UI, or `BeforeEnterObserver` on `MainLayout` or similar.
4. Don't use Spring at all :+1: I believe Kotlin makes Spring obsolete - if you can use Kotlin, perhaps you can try https://www.vaadinonkotlin.eu/ which has security baked in.

**Comment by hendrick404** [comment]
Hi Martin, I'm also a student, working with Dennis and Leo. Thank you very much for your support. We were able to solve our problem by using the first attempt and manually setting the Spring authentication. Like described here https://www.baeldung.com/manually-set-user-authentication-spring-security.

**Comment by mvysny** [comment]
Awesome, thank you for letting me know. I'll update the docs to include the workaround for Spring Security :+1:

**Comment by mvysny** [comment]
I've created an example project which demoes the spring security+karibu testing integration: https://github.com/mvysny/vaadin-spring-karibu-testing

**Comment by mvysny** [comment]
Solved: the trick is to set the user principal in `MockRequest`, and also provide a proper implementation of `MockRequest.isUserInRole()`.
