### ISSUE TITLE
Add support for selecting table rows

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#5]
I ended up using Grid.select() api, but it would be nice if there was support in karibu for this type of operation.

**Comment by mvysny** [comment]
I'm striving here to provide testing support only (say an assert on the current selection state) rather than to complement the existing API. So you should use an existing grid API if you wish rows to being selected.

With that being said, it could be so that an useful selection function is missing which would help with the testing. Could you please provide details on your use case, and what kind of selection method you are missing and why the current ones are lacking?
